spring.application.name=Budget-App
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/budget-app
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true